### ISSUE TITLE
extract_fit() results in error

### ISSUE THREAD

**Issue by yrosseel** [milanwiedemann/lcsm#11]
This came up during rev dep checks of lavaan: the example for 'extract_fit' results in the error:
```r
Error in lavInspect(x, "converged") : 
  could not find function "lavInspect"
```
This is also shown on CRAN checks: https://cran.r-project.org/web/checks/check_results_lcsm.html

This is probably due to recent changes in broom.

Yves.

**Comment by yrosseel** [comment]
I see now that you have already requested a pull request  in tidymodels/broom to fix this. Thanks!

**Comment by milanwiedemann** [comment]
thanks! cran had also notified me about the error and broom merged my pull request so all working again 👍
