### ISSUE TITLE
two time points latent change score analysis

### ISSUE THREAD

**Issue by wanglu2014** [milanwiedemann/lcsm#7]
There are data of two time points: before and after the dietary intervention. Follow the following hypothesis; we have been planning to carry out latent change score analysis.
An example of our data has been attached, could you kindly provide the suggestion on model building for it? Both lavaan or openMx were good enough.
Thank you for your help!
[meta_toy.zip](https://github.com/milanwiedemann/lcsm/files/3599821/meta_toy.zip)
![meta_toyh](https://user-images.githubusercontent.com/12541282/64682188-a55bc480-d4b3-11e9-8289-91c863dedb4d.png)

**Comment by milanwiedemann** [comment]
Thanks, I can have a look next week at some point. There is a great tutorial paper by Kievit et al. ([2018](https://www.sciencedirect.com/science/article/pii/S187892931730021X)). The examples in their paper also have two time points and the code is available [here](https://osf.io/4bpmq/files/).
